# Azure AI Foundry - Unified Deployment Pipeline
# Deploys guardrails, connections, and agents in the correct order with dependency validation

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infrastructure/**
      - agents/**
      - scripts/**
      - pipelines/azure-devops-pipeline.yml

# Runtime parameters for selective deployment
parameters:
  - name: deployGuardrails
    displayName: 'Deploy Guardrails (Content Filters)'
    type: boolean
    default: true
  
  - name: deployConnections
    displayName: 'Deploy Connections (API Tools)'
    type: boolean
    default: true
  
  - name: deployAgents
    displayName: 'Deploy Agents'
    type: boolean
    default: true
  
  - name: agentFile
    displayName: 'Agent File to Deploy (leave empty for all)'
    type: string
    default: 'agents/weather-agent.yaml'

variables:
  - name: AZURE_SERVICE_CONNECTION
    value: 'ado-service-connection'
  - name: RESOURCE_GROUP
    value: 'ad-usa-poc'
  - name: AI_FOUNDRY_ENDPOINT
    value: 'https://adusa-poc-agent.services.ai.azure.com/api/projects/adusa-poc-agent'

pool:
  name: 'egen-agent-pool'

stages:
  # ============================================================================
  # STAGE 1: GUARDRAILS (Content Filters & PII Protection)
  # ============================================================================
  - stage: DeployGuardrails
    displayName: '🛡️ Deploy Guardrails'
    condition: eq('${{ parameters.deployGuardrails }}', true)
    jobs:
      - job: DeployContentFilters
        displayName: 'Deploy Content Filters'
        steps:
          - checkout: self
          
          - bash: |
              echo "=============================================="
              echo "🛡️  DEPLOYING GUARDRAILS"
              echo "=============================================="
              echo "Template: infrastructure/modules/guardrails/content_filter.bicep"
              echo "Parameters: infrastructure/parameters/guardrails/guardrails.bicepparam"
              echo "=============================================="
            displayName: '📋 Show deployment info'
          
          - task: AzureCLI@2
            displayName: '✅ Validate Bicep template'
            inputs:
              azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Validating Bicep template..."
                az bicep build --file infrastructure/modules/guardrails/content_filter.bicep
                echo "✅ Template is valid"
          
          - task: AzureCLI@2
            displayName: '🚀 Deploy Guardrails'
            inputs:
              azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Deploying content filters..."
                az deployment group create \
                  --resource-group $(RESOURCE_GROUP) \
                  --template-file infrastructure/modules/guardrails/content_filter.bicep \
                  --parameters infrastructure/parameters/guardrails/guardrails.bicepparam \
                  --name "guardrails-$(Build.BuildId)"
                
                echo "✅ Guardrails deployed successfully"
          
          - task: AzureCLI@2
            displayName: '🔍 Verify Deployment'
            inputs:
              azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Verifying deployment..."
                STATUS=$(az deployment group show \
                  --resource-group $(RESOURCE_GROUP) \
                  --name "guardrails-$(Build.BuildId)" \
                  --query "properties.provisioningState" -o tsv)
                
                if [ "$STATUS" != "Succeeded" ]; then
                  echo "❌ Deployment failed with status: $STATUS"
                  exit 1
                fi
                
                echo "✅ Deployment verified: $STATUS"

  # ============================================================================
  # STAGE 2: CONNECTIONS (API Tools)
  # ============================================================================
  - stage: DeployConnections
    displayName: '🔌 Deploy Connections'
    dependsOn: DeployGuardrails
    condition: |
      and(
        eq('${{ parameters.deployConnections }}', true),
        or(
          succeeded(),
          eq('${{ parameters.deployGuardrails }}', false)
        )
      )
    jobs:
      - job: DeployAPIConnections
        displayName: 'Deploy API Connections'
        steps:
          - checkout: self
          
          - bash: |
              echo "=============================================="
              echo "🔌 DEPLOYING CONNECTIONS"
              echo "=============================================="
              echo "Template: infrastructure/modules/connections/connection.bicep"
              echo "Parameters: infrastructure/parameters/connections/connections.bicepparam"
              echo "=============================================="
            displayName: '📋 Show deployment info'
          
          - bash: |
              echo "Creating virtual environment..."
              python3 -m venv .venv
              source .venv/bin/activate
              echo "Installing dependencies..."
              pip install -q -r requirements.txt
            displayName: '📦 Install dependencies'
          
          - task: AzureCLI@2
            displayName: '✅ Validate Bicep template'
            inputs:
              azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Validating Bicep template..."
                az bicep build --file infrastructure/modules/connections/connection.bicep
                echo "✅ Template is valid"
          
          - task: AzureCLI@2
            displayName: '🚀 Deploy Connections'
            inputs:
              azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Deploying connections..."
                source .venv/bin/activate
                python scripts/deploy_infrastructure.py foundry_connection \
                  --bicepparam infrastructure/parameters/connections/connections.bicepparam
                
                echo "✅ Connections deployed successfully"

  # ============================================================================
  # STAGE 3: AGENTS (with dependency validation)
  # ============================================================================
  - stage: DeployAgents
    displayName: '🤖 Deploy Agents'
    dependsOn: 
      - DeployGuardrails
      - DeployConnections
    condition: |
      and(
        eq('${{ parameters.deployAgents }}', true),
        or(
          succeeded(),
          and(
            eq('${{ parameters.deployGuardrails }}', false),
            eq('${{ parameters.deployConnections }}', false)
          )
        )
      )
    jobs:
      - job: ValidateDependencies
        displayName: 'Validate Agent Dependencies'
        steps:
          - checkout: self
          
          - bash: |
              echo "Creating virtual environment..."
              python3 -m venv .venv
              source .venv/bin/activate
              pip install -q pyyaml
            displayName: '📦 Install PyYAML'
          
          - bash: |
              echo "=============================================="
              echo "🔍 VALIDATING AGENT DEPENDENCIES"
              echo "=============================================="
              
              AGENT_FILE="${{ parameters.agentFile }}"
              
              if [ -z "$AGENT_FILE" ]; then
                echo "No specific agent file provided, will deploy all agents"
                AGENT_FILE="agents/weather-agent.yaml"
              fi
              
              echo "Checking agent file: $AGENT_FILE"
              
              if [ ! -f "$AGENT_FILE" ]; then
                echo "❌ Agent file not found: $AGENT_FILE"
                exit 1
              fi
              
              # Parse agent YAML and check for tool dependencies
              source .venv/bin/activate
              python << 'EOF'
              import yaml
              import sys
              import os
              
              agent_file = "${{ parameters.agentFile }}" or "agents/weather-agent.yaml"
              
              print(f"📄 Parsing {agent_file}...")
              
              with open(agent_file, 'r') as f:
                  agent_config = yaml.safe_load(f)
              
              # Check for tools
              tools = agent_config.get('tools', [])
              required_connections = []
              
              for tool in tools:
                  tool_type = tool.get('type')
                  if tool_type == 'openapi':
                      connection_id = tool.get('options', {}).get('connection_id')
                      if connection_id:
                          required_connections.append(connection_id)
                          print(f"  ✓ Found required connection: {connection_id}")
              
              # Check if connections were deployed
              deploy_connections = "${{ parameters.deployConnections }}" == "true"
              
              if required_connections and not deploy_connections:
                  print("\n❌ ERROR: Agent requires connections but 'Deploy Connections' was not selected!")
                  print(f"   Required connections: {', '.join(required_connections)}")
                  print("\n   Please either:")
                  print("   1. Enable 'Deploy Connections' checkbox, OR")
                  print("   2. Ensure connections are already deployed")
                  sys.exit(1)
              
              # Check if guardrails are referenced
              guardrails = agent_config.get('guardrails', {})
              deploy_guardrails = "${{ parameters.deployGuardrails }}" == "true"
              
              if guardrails and not deploy_guardrails:
                  print("\n⚠️  WARNING: Agent references guardrails but 'Deploy Guardrails' was not selected")
                  print("   Guardrails should be deployed before agents for proper protection")
              
              print("\n✅ Dependency validation passed")
              EOF
              
              echo "=============================================="
            displayName: '🔍 Validate dependencies'
            failOnStderr: false
      
      - job: DeployAgentJob
        displayName: 'Deploy Agent'
        dependsOn: ValidateDependencies
        steps:
          - checkout: self
          
          - bash: |
              echo "Creating virtual environment..."
              python3 -m venv .venv
              source .venv/bin/activate
              echo "Installing dependencies..."
              pip install -q -r requirements.txt
            displayName: '📦 Install dependencies'
          
          - task: AzureCLI@2
            displayName: '🚀 Deploy Agent'
            inputs:
              azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "=============================================="
                echo "🤖 DEPLOYING AGENT"
                echo "=============================================="
                
                AGENT_FILE="${{ parameters.agentFile }}"
                
                if [ -z "$AGENT_FILE" ]; then
                  AGENT_FILE="agents/weather-agent.yaml"
                fi
                
                echo "Agent file: $AGENT_FILE"
                echo "Endpoint: $(AI_FOUNDRY_ENDPOINT)"
                echo ""
                
                source .venv/bin/activate
                python -m scripts.deploy_agent \
                  "$(AI_FOUNDRY_ENDPOINT)" \
                  "$AGENT_FILE"
                
                echo ""
                echo "✅ Agent deployed successfully"
                echo "=============================================="

  # ============================================================================
  # STAGE 4: SUMMARY
  # ============================================================================
  - stage: DeploymentSummary
    displayName: '📊 Deployment Summary'
    dependsOn:
      - DeployGuardrails
      - DeployConnections
      - DeployAgents
    condition: always()
    jobs:
      - job: ShowSummary
        displayName: 'Show Deployment Summary'
        steps:
          - bash: |
              echo "=============================================="
              echo "📊 DEPLOYMENT SUMMARY"
              echo "=============================================="
              echo ""
              echo "Deployment Selections:"
              echo "  🛡️  Guardrails:  ${{ parameters.deployGuardrails }}"
              echo "  🔌 Connections: ${{ parameters.deployConnections }}"
              echo "  🤖 Agents:      ${{ parameters.deployAgents }}"
              echo ""
              echo "Agent File: ${{ parameters.agentFile }}"
              echo ""
              echo "Build ID: $(Build.BuildId)"
              echo "=============================================="
            displayName: '📋 Summary'
